apiVersion: v1
kind: Service
metadata:
  name: cjq-claw
  labels:
    app: cjq-claw
spec:
  type: ClusterIP
  selector:
    app: cjq-claw
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
